- name: create a new ec2 key pair for bastion server
  ec2_key:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    name: key_for_bastion
    key_material: "{{ lookup('file', '/home/artemkubrachenko/.ssh/id_rsa.pub') }}"
  register: key_for_bastion

- name: Create bastion EC2 instances in subnet1
  ec2_instance:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "Bastion"
    image_id: ami-0112d42866980b373
    state: "present"
    instance_type:  t2.micro
    region: "{{ region }}"
    security_group: "{{ security_group.group_id }}"
    vpc_subnet_id: "{{ subnet2.subnet.id }}"
    wait: yes
    key_name: "key_for_bastion"
    network:
      assign_public_ip: true
    tags: "{{ resource_tags }}"
  register: aws_ec2_bastion

- name: Wait for SSH to come up
  wait_for:
    host: "{{ aws_ec2_bastion.instances[0].public_ip_address }}"
    port: 22
    state: started

- name: Scan key
  shell: ssh-keyscan -H {{ aws_ec2_bastion.instances[0].public_ip_address }} >> ~/.ssh/known_hosts

- name: Load template for ssh proxy ~/.ssh/config
  vars:
    ssh_key_path: "/home/artemkubrachenko/.ssh/id_rsa"
    proxy_ip: "{{ hostvars['localhost'].aws_ec2_bastion.instances[0].public_ip_address }}"
  template: dest="~/.ssh/config" src="ssh_config.j2"