---
- name: create a new ec2 key pair for get server
  ec2_key:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    name: key_for_get
    key_material: "{{ lookup('file', '/home/artemkubrachenko/.ssh/id_rsa.pub') }}"
  register: key_for_get

- name: Create EC2 get server
  ec2_instance:
    name: get-server
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    wait: yes
    image_id: ami-0112d42866980b373
    instance_type: t2.micro
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    security_group: "{{ security_group.group_id }}"
    tags: "{{ resource_tags }}"
    key_name: "{{ key_for_get.key.name }}"
    state: present
    network:
      assign_public_ip: false
  register: ec2get

- name: add host get server to group 'ec2hosts'
  add_host:
    name: "{{ ec2get.instances[0].private_ip_address }}"
    groups: ec2get
    ansible_user: ec2-user
    ansible_shh_private_key_file: /home/artemkubrachenko/.ssh/id_rsa